// @ts-nocheck
/**
 * Generate the ExtendScript (.jsx) that dumps a project's After Effects render
 * queue to a JSON file. aerender can't enumerate the queue, so we script the
 * full AfterFX.exe binary headlessly (`AfterFX.exe -noui -r inspect.jsx`).
 *
 * For each QUEUED render-queue item the script reports: the AE render-queue
 * index, comp name, fps, frame range (derived from the item's time span), the
 * output module's filename + extension, and whether that output is an image
 * sequence (filename carries a [#####] placeholder) or a single movie.
 *
 * Spec: AE-RENDER-FARM-SPEC.md, "Render-queue inspection".
 */

/** Escape a Windows path for embedding in a JSX string literal (use / separators). */
function toJsxPath(p: string): string {
  return p.replace(/\\/g, '/').replace(/"/g, '\\"')
}

export function buildInspectJsx(projectPath: string, outJsonPath: string): string {
  const proj = toJsxPath(projectPath)
  const out = toJsxPath(outJsonPath)
  return `
// Auto-generated by kit-render-worker — dumps the render queue to JSON.
(function () {
  function frameOf(seconds, fps) { return Math.round(seconds * fps); }
  var result = { items: [], error: null };
  try {
    app.exitAfterLaunchAndEval = false;
    var projFile = new File("${proj}");
    app.open(projFile);
    var rq = app.project.renderQueue;
    for (var i = 1; i <= rq.numItems; i++) {
      var item = rq.item(i);
      // Only items that are actually queued for render.
      if (item.status !== RQItemStatus.QUEUED) continue;
      var comp = item.comp;
      var fps = comp.frameRate;
      var startFrame = frameOf(item.timeSpanStart, fps);
      var durFrames = frameOf(item.timeSpanDuration, fps);
      var endFrame = startFrame + durFrames - 1;
      var outName = "";
      try {
        var om = item.outputModule(1);
        if (om && om.file) outName = om.file.name;
      } catch (e) {}
      var isSeq = /\\[#+\\]/.test(outName) || /#/.test(outName);
      result.items.push({
        rqindex: i,
        comp: comp.name,
        fps: fps,
        frameStart: startFrame,
        frameEnd: endFrame,
        totalFrames: durFrames,
        outputName: outName,
        isSequence: isSeq
      });
    }
  } catch (e) {
    result.error = e.toString();
  }
  var f = new File("${out}");
  f.encoding = "UTF-8";
  f.open("w");
  f.write(JSON.stringify(result));
  f.close();
  app.quit();
})();
`.trim()
}
