/**
 * Pilots — deterministic, read-only Canvas projection.
 *
 * Pure, no I/O. Renders the entire dedicated pilot Canvas from the authoritative
 * snapshot. The render is total and deterministic, so re-rendering the same
 * snapshot always yields the same markdown (idempotent). Canvas prose is NEVER
 * an input — only the snapshot is — so a manual Canvas edit can never become
 * source state.
 *
 * The rendered document keeps the mission's evidence categories VISUALLY
 * SEPARATED: measured results, observations, artist judgments, assumptions,
 * unknowns, risks, technical validation, and the final decision are distinct
 * sections. Derived metrics come from the deterministic metrics owner.
 */

import { computePilotMetrics, formatUsableOutputRate } from './metrics'
import { evaluateCompleteness } from './completeness'
import type { EvidenceRow, PilotSnapshot } from './types'

/**
 * Prominent banner making the read-only / projection contract visible in the
 * artifact itself: Supabase is authoritative, this Canvas is a generated
 * projection, and edits made here are not read back.
 */
export const PILOT_GENERATED_VIEW_NOTICE =
  '> 🔒 **Generated view — do not edit here.**\n' +
  '> This canvas is generated by Kit from the pilot’s structured evidence (the authoritative source). ' +
  'Record changes through Kit; edits made directly to this canvas are **not** read back and will be **overwritten**.'

function esc(v: string | null | undefined): string {
  return (v ?? '').replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim()
}

function section(title: string, body: string): string {
  return `## ${title}\n\n${body}\n`
}

function bullet(lines: string[]): string {
  return lines.length ? lines.map((l) => `- ${l}`).join('\n') : '_None recorded._'
}

function evidenceLines(rows: EvidenceRow[]): string[] {
  return rows.map((e) => {
    const label = esc(e.label) || '(unlabeled)'
    if (e.category === 'measurement') {
      const val = e.value_numeric != null ? `${e.value_numeric}${e.unit ? ` ${esc(e.unit)}` : ''}` : esc(e.value_text)
      const key = e.metric_key ? `\`${esc(e.metric_key)}\` ` : ''
      return `${key}**${label}**: ${val || '—'}  _(by ${esc(e.author)})_`
    }
    const text = esc(e.value_text) || label
    return `**${label}**: ${text}  _(by ${esc(e.author)})_`
  })
}

function byCategory(s: PilotSnapshot, category: EvidenceRow['category']): EvidenceRow[] {
  return s.evidence.filter((e) => e.category === category)
}

/**
 * Render the full pilot Canvas markdown from the snapshot. Deterministic: the
 * same snapshot always produces the same document.
 */
export function renderPilotCanvas(snapshot: PilotSnapshot): string {
  const p = snapshot.pilot
  const metrics = computePilotMetrics(snapshot.generations)
  const completeness = evaluateCompleteness(snapshot)

  const title = `# ${esc(p.title) || 'Visual Development Pilot'}`
  const header =
    `**Type:** ${esc(p.pilot_type)}  ·  **Status:** ${esc(p.status)}  ·  **Project:** ${esc(p.project_id)}`

  const refs = snapshot.references
  const pinterest = refs.filter((r) => r.ref_type === 'pinterest')
  const figma = refs.filter((r) => r.ref_type === 'figma_moodboard')
  const styleframes = refs.filter((r) => r.ref_type === 'styleframe_direction')

  const researchBody = [
    '**Pinterest research:**',
    bullet(pinterest.map((r) => `[${esc(r.label) || 'pin'}](${esc(r.url)})`)),
    '',
    '**Figma moodboard:**',
    bullet(figma.map((r) => `[${esc(r.label) || 'moodboard'}](${esc(r.url)})`)),
    '',
    '**Styleframe directions:**',
    bullet(styleframes.map((r) => `${esc(r.label) || '(direction)'}${r.description ? ` — ${esc(r.description)}` : ''}`)),
  ].join('\n')

  const visualLanguageBody = p.visual_language ? esc(p.visual_language) : '_Not yet defined._'

  const genBody = bullet(
    snapshot.generations.map(
      (g) =>
        `[${g.acceptance.toUpperCase()}] ${esc(g.label) || esc(g.kind) || 'output'}` +
        `${g.external_ref ? ` — ${esc(g.external_ref)}` : ''}` +
        `${g.acceptance === 'accepted' && g.accepted_by ? `  _(accepted by ${esc(g.accepted_by)})_` : ''}`,
    ),
  )

  const metricsBody = [
    `- **Total outputs:** ${metrics.totalGenerations}`,
    `- **Human-accepted (usable):** ${metrics.usableGenerations}`,
    `- **Rejected:** ${metrics.rejectedGenerations}`,
    `- **Pending:** ${metrics.pendingGenerations}`,
    `- **Usable-output rate:** ${formatUsableOutputRate(metrics.usableOutputRate)}`,
  ].join('\n')

  // Materials grouped by package.
  const pkgNames = [...new Set(snapshot.materialMaps.map((m) => m.package_name))]
  const materialsBody = pkgNames.length
    ? pkgNames
        .map((pkg) => {
          const maps = snapshot.materialMaps.filter((m) => m.package_name === pkg)
          const mapLines = maps.map((m) => `  - \`${esc(m.map_type)}\` — purpose: ${esc(m.purpose)}`)
          return `- **${esc(pkg)}**\n${mapLines.join('\n')}`
        })
        .join('\n')
    : '_No material packages recorded._'

  const validationBody = bullet(
    snapshot.validations.map(
      (v) => `**${esc(v.tool)}** — ${v.passed ? '✅ passed' : '❌ failed'} — evidence: ${esc(v.evidence_ref)}${v.subject ? ` (${esc(v.subject)})` : ''}`,
    ),
  )

  const decisionBody = (() => {
    if (p.status === 'finalized' && p.recommendation) {
      return [
        `**Recommendation:** ${esc(p.recommendation).toUpperCase()}`,
        p.recommendation_rationale ? `\n${esc(p.recommendation_rationale)}` : '',
        `\n_Entered by ${esc(p.recommendation_by)}${p.recommendation_at ? ` at ${esc(p.recommendation_at)}` : ''}._`,
        '\n\n**Supporting evidence (decisions):**',
        bullet(evidenceLines(byCategory(snapshot, 'decision'))),
      ].join('')
    }
    if (p.status === 'abandoned') return '_Pilot abandoned._'
    const missing = completeness.missing.map((m) => m.detail)
    return [
      '_No final recommendation yet — the evidence-completeness gate has not passed._',
      '',
      '**Outstanding before finalization:**',
      bullet(missing),
    ].join('\n')
  })()

  return [
    PILOT_GENERATED_VIEW_NOTICE,
    '',
    title,
    '',
    header,
    '',
    section('Research & References', researchBody),
    section('Visual Language', visualLanguageBody),
    section('Generated Outputs', genBody),
    section('Measured Results', metricsBody + '\n\n' + bullet(evidenceLines(byCategory(snapshot, 'measurement')))),
    section('Observations', bullet(evidenceLines(byCategory(snapshot, 'observation')))),
    section('Artist Judgments', bullet(evidenceLines(byCategory(snapshot, 'judgment')))),
    section('Assumptions', bullet(evidenceLines(byCategory(snapshot, 'assumption')))),
    section('Unknowns', bullet(evidenceLines(byCategory(snapshot, 'unknown')))),
    section('Risks', bullet(evidenceLines(byCategory(snapshot, 'risk')))),
    section('Material Packages', materialsBody),
    section('Technical Validation (Cinema 4D / Redshift)', validationBody),
    section('Final Decision', decisionBody),
  ].join('\n')
}
